
import Layout from "@/components/layout/Layout";
import localFont from 'next/font/local'
import "./globals.css"

const PoetsenOneFont = localFont({src:"../../public/fonts/PoetsenOne-Regular.ttf" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={PoetsenOneFont.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
